services:
  - type: web
    name: quickbite-backend
    runtime: node
    buildCommand: yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: quickbite-backend
          property: port
      - key: OPENAI_API_KEY
        value: your-openai-api-key-here
      - key: OPENAI_MODEL
        value: gpt-3.5-turbo
    healthCheckPath: /api/health
    disk:
      name: quickbite-disk
      mountPath: /data
      sizeGB: 1
